from fastapi import FastAPI, File, UploadFile, HTTPException
import onnxruntime as ort
import numpy as np
import tempfile
import os
import shutil
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="HortiVision AI Inference Server")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Constants ────────────────────────────────────────────────
CLASS_NAMES      = ["muscadine_copper", "muscadine_darkpurple", "muscadine_purple"]
CLASSIFIER_SCALE = 24066.9

# ── Load ONNX model ──────────────────────────────────────────
MODEL_PATH  = "models/mobilevit_rawbil_hsi8.onnx"
session     = ort.InferenceSession(MODEL_PATH)
input_name  = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name

print(f"Model loaded: {MODEL_PATH}")
print(f"Input : {input_name} {session.get_inputs()[0].shape}")
print(f"Output: {output_name} {session.get_outputs()[0].shape}")


def softmax_fn(logits: np.ndarray) -> np.ndarray:
    e = np.exp(logits - np.max(logits))
    return e / e.sum()


# ── Routes ───────────────────────────────────────────────────

@app.get("/")
def root():
    return {
        "status" : "HortiVision AI inference server running",
        "model"  : "MobileViT HSI8 — Muscadine Grape Classifier",
        "classes": CLASS_NAMES,
        "upload" : "POST /predict with classifier_crop_224_hsi8.npz"
    }


@app.post("/predict")
async def predict(
    npz_file: UploadFile = File(..., description="classifier_crop_224_hsi8.npz from pipeline")
):
    """
    Accepts the pre-processed .npz file generated by the local pipeline.
    The .npz contains the 8-band 224x224 crop ready for ONNX inference.
    File size is ~400KB vs 270MB for raw .bil — works on free tier.
    """
    tmp_dir = tempfile.mkdtemp()
    try:
        npz_path = os.path.join(tmp_dir, "input.npz")

        # Save uploaded file
        with open(npz_path, "wb") as f:
            f.write(await npz_file.read())

        # Load npz
        data = np.load(npz_path)

        # The pipeline saves the array — find the correct key
        keys = list(data.keys())
        if len(keys) == 0:
            raise HTTPException(status_code=400, detail="Empty .npz file")

        # Use first array found — pipeline saves as 'arr_0' or named key
        arr = data[keys[0]].astype(np.float32)

        # Expected shape: (224, 224, 8) or (1, 8, 224, 224) or (8, 224, 224)
        if arr.ndim == 3 and arr.shape == (224, 224, 8):
            # HWC → CHW → NCHW
            arr = np.transpose(arr, (2, 0, 1))
            arr = np.expand_dims(arr, axis=0)
        elif arr.ndim == 3 and arr.shape == (8, 224, 224):
            # CHW → NCHW
            arr = np.expand_dims(arr, axis=0)
        elif arr.ndim == 4 and arr.shape == (1, 8, 224, 224):
            # Already NCHW
            pass
        else:
            raise HTTPException(
                status_code=400,
                detail=f"Unexpected array shape: {arr.shape}. Expected (224,224,8) or (1,8,224,224)"
            )

        # Run ONNX inference
        logits = session.run([output_name], {input_name: arr})[0][0]
        probs  = softmax_fn(logits)

        pred_index    = int(np.argmax(probs))
        prediction    = CLASS_NAMES[pred_index]
        confidence    = float(probs[pred_index])
        probabilities = {CLASS_NAMES[i]: float(probs[i]) for i in range(len(CLASS_NAMES))}

        return {
            "ok"           : True,
            "prediction"   : prediction,
            "confidence"   : round(confidence * 100, 4),
            "probabilities": {k: round(v * 100, 6) for k, v in probabilities.items()},
            "npz_keys"     : keys,
            "input_shape"  : list(arr.shape)
        }

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


@app.get("/health")
def health():
    return {"status": "ok"}